// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface AppBroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.AppBroadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Triggers a BEB broadcast containing AppValue populated with the value from AppBroadcast
   * </pre>
   *
   * <code>.main.Value value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * Triggers a BEB broadcast containing AppValue populated with the value from AppBroadcast
   * </pre>
   *
   * <code>.main.Value value = 1;</code>
   * @return The value.
   */
  networking.Value getValue();
  /**
   * <pre>
   * Triggers a BEB broadcast containing AppValue populated with the value from AppBroadcast
   * </pre>
   *
   * <code>.main.Value value = 1;</code>
   */
  networking.ValueOrBuilder getValueOrBuilder();
}
