// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface AppDecideOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.AppDecide)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Decided value taken from UcDecide
   * </pre>
   *
   * <code>.main.Value value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * Decided value taken from UcDecide
   * </pre>
   *
   * <code>.main.Value value = 1;</code>
   * @return The value.
   */
  networking.Value getValue();
  /**
   * <pre>
   * Decided value taken from UcDecide
   * </pre>
   *
   * <code>.main.Value value = 1;</code>
   */
  networking.ValueOrBuilder getValueOrBuilder();
}
