// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface AppProposeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.AppPropose)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The topic on which to reach consensus. There will be a consensus instance for each topic
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * The topic on which to reach consensus. There will be a consensus instance for each topic
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   * Random value chosen by the HUB
   * </pre>
   *
   * <code>.main.Value value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * Random value chosen by the HUB
   * </pre>
   *
   * <code>.main.Value value = 2;</code>
   * @return The value.
   */
  networking.Value getValue();
  /**
   * <pre>
   * Random value chosen by the HUB
   * </pre>
   *
   * <code>.main.Value value = 2;</code>
   */
  networking.ValueOrBuilder getValueOrBuilder();
}
