// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface AppWriteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.AppWrite)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string register = 1;</code>
   * @return The register.
   */
  java.lang.String getRegister();
  /**
   * <code>string register = 1;</code>
   * @return The bytes for register.
   */
  com.google.protobuf.ByteString
      getRegisterBytes();

  /**
   * <pre>
   * Value to write in the register
   * </pre>
   *
   * <code>.main.Value value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * Value to write in the register
   * </pre>
   *
   * <code>.main.Value value = 2;</code>
   * @return The value.
   */
  networking.Value getValue();
  /**
   * <pre>
   * Value to write in the register
   * </pre>
   *
   * <code>.main.Value value = 2;</code>
   */
  networking.ValueOrBuilder getValueOrBuilder();
}
