// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface AppWriteReturnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.AppWriteReturn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string register = 1;</code>
   * @return The register.
   */
  java.lang.String getRegister();
  /**
   * <code>string register = 1;</code>
   * @return The bytes for register.
   */
  com.google.protobuf.ByteString
      getRegisterBytes();
}
