// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface BebBroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.BebBroadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.main.Message message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.main.Message message = 1;</code>
   * @return The message.
   */
  networking.Message getMessage();
  /**
   * <code>.main.Message message = 1;</code>
   */
  networking.MessageOrBuilder getMessageOrBuilder();
}
