// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface BebDeliverOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.BebDeliver)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.main.Message message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.main.Message message = 1;</code>
   * @return The message.
   */
  networking.Message getMessage();
  /**
   * <code>.main.Message message = 1;</code>
   */
  networking.MessageOrBuilder getMessageOrBuilder();

  /**
   * <code>.main.ProcessId sender = 2;</code>
   * @return Whether the sender field is set.
   */
  boolean hasSender();
  /**
   * <code>.main.ProcessId sender = 2;</code>
   * @return The sender.
   */
  networking.ProcessId getSender();
  /**
   * <code>.main.ProcessId sender = 2;</code>
   */
  networking.ProcessIdOrBuilder getSenderOrBuilder();
}
