// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface EcInternalNewEpochOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.EcInternalNewEpoch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 timestamp = 1;</code>
   * @return The timestamp.
   */
  int getTimestamp();
}
