// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface EldTrustOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.EldTrust)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.main.ProcessId process = 1;</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.main.ProcessId process = 1;</code>
   * @return The process.
   */
  networking.ProcessId getProcess();
  /**
   * <code>.main.ProcessId process = 1;</code>
   */
  networking.ProcessIdOrBuilder getProcessOrBuilder();
}
