// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface EpAbortedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.EpAborted)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Needed to know in UC the timestamp of the EP, where the algorithm says "such that ts = ets do"
   * </pre>
   *
   * <code>int32 ets = 1;</code>
   * @return The ets.
   */
  int getEts();

  /**
   * <pre>
   * The timestamp part of the "state" mentioned in the algorithm
   * </pre>
   *
   * <code>int32 valueTimestamp = 2;</code>
   * @return The valueTimestamp.
   */
  int getValueTimestamp();

  /**
   * <pre>
   * The value part of the "state" mentioned in the algorithm
   * </pre>
   *
   * <code>.main.Value value = 3;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * The value part of the "state" mentioned in the algorithm
   * </pre>
   *
   * <code>.main.Value value = 3;</code>
   * @return The value.
   */
  networking.Value getValue();
  /**
   * <pre>
   * The value part of the "state" mentioned in the algorithm
   * </pre>
   *
   * <code>.main.Value value = 3;</code>
   */
  networking.ValueOrBuilder getValueOrBuilder();
}
