// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface EpfdTimeoutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.EpfdTimeout)
    com.google.protobuf.MessageOrBuilder {
}
