// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

/**
 * Protobuf type {@code main.EpfdSuspect}
 */
public final class EpfdSuspect extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:main.EpfdSuspect)
    EpfdSuspectOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      EpfdSuspect.class.getName());
  }
  // Use EpfdSuspect.newBuilder() to construct.
  private EpfdSuspect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EpfdSuspect() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return networking.CommunicationProtocol.internal_static_main_EpfdSuspect_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return networking.CommunicationProtocol.internal_static_main_EpfdSuspect_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            networking.EpfdSuspect.class, networking.EpfdSuspect.Builder.class);
  }

  private int bitField0_;
  public static final int PROCESS_FIELD_NUMBER = 1;
  private networking.ProcessId process_;
  /**
   * <code>.main.ProcessId process = 1;</code>
   * @return Whether the process field is set.
   */
  @java.lang.Override
  public boolean hasProcess() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.main.ProcessId process = 1;</code>
   * @return The process.
   */
  @java.lang.Override
  public networking.ProcessId getProcess() {
    return process_ == null ? networking.ProcessId.getDefaultInstance() : process_;
  }
  /**
   * <code>.main.ProcessId process = 1;</code>
   */
  @java.lang.Override
  public networking.ProcessIdOrBuilder getProcessOrBuilder() {
    return process_ == null ? networking.ProcessId.getDefaultInstance() : process_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getProcess());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProcess());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof networking.EpfdSuspect)) {
      return super.equals(obj);
    }
    networking.EpfdSuspect other = (networking.EpfdSuspect) obj;

    if (hasProcess() != other.hasProcess()) return false;
    if (hasProcess()) {
      if (!getProcess()
          .equals(other.getProcess())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProcess()) {
      hash = (37 * hash) + PROCESS_FIELD_NUMBER;
      hash = (53 * hash) + getProcess().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static networking.EpfdSuspect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.EpfdSuspect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.EpfdSuspect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.EpfdSuspect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.EpfdSuspect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.EpfdSuspect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.EpfdSuspect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.EpfdSuspect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static networking.EpfdSuspect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static networking.EpfdSuspect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static networking.EpfdSuspect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.EpfdSuspect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(networking.EpfdSuspect prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code main.EpfdSuspect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:main.EpfdSuspect)
      networking.EpfdSuspectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return networking.CommunicationProtocol.internal_static_main_EpfdSuspect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return networking.CommunicationProtocol.internal_static_main_EpfdSuspect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              networking.EpfdSuspect.class, networking.EpfdSuspect.Builder.class);
    }

    // Construct using networking.EpfdSuspect.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getProcessFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return networking.CommunicationProtocol.internal_static_main_EpfdSuspect_descriptor;
    }

    @java.lang.Override
    public networking.EpfdSuspect getDefaultInstanceForType() {
      return networking.EpfdSuspect.getDefaultInstance();
    }

    @java.lang.Override
    public networking.EpfdSuspect build() {
      networking.EpfdSuspect result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public networking.EpfdSuspect buildPartial() {
      networking.EpfdSuspect result = new networking.EpfdSuspect(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(networking.EpfdSuspect result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.process_ = processBuilder_ == null
            ? process_
            : processBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof networking.EpfdSuspect) {
        return mergeFrom((networking.EpfdSuspect)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(networking.EpfdSuspect other) {
      if (other == networking.EpfdSuspect.getDefaultInstance()) return this;
      if (other.hasProcess()) {
        mergeProcess(other.getProcess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getProcessFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private networking.ProcessId process_;
    private com.google.protobuf.SingleFieldBuilder<
        networking.ProcessId, networking.ProcessId.Builder, networking.ProcessIdOrBuilder> processBuilder_;
    /**
     * <code>.main.ProcessId process = 1;</code>
     * @return Whether the process field is set.
     */
    public boolean hasProcess() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     * @return The process.
     */
    public networking.ProcessId getProcess() {
      if (processBuilder_ == null) {
        return process_ == null ? networking.ProcessId.getDefaultInstance() : process_;
      } else {
        return processBuilder_.getMessage();
      }
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     */
    public Builder setProcess(networking.ProcessId value) {
      if (processBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        process_ = value;
      } else {
        processBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     */
    public Builder setProcess(
        networking.ProcessId.Builder builderForValue) {
      if (processBuilder_ == null) {
        process_ = builderForValue.build();
      } else {
        processBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     */
    public Builder mergeProcess(networking.ProcessId value) {
      if (processBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          process_ != null &&
          process_ != networking.ProcessId.getDefaultInstance()) {
          getProcessBuilder().mergeFrom(value);
        } else {
          process_ = value;
        }
      } else {
        processBuilder_.mergeFrom(value);
      }
      if (process_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     */
    public Builder clearProcess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     */
    public networking.ProcessId.Builder getProcessBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getProcessFieldBuilder().getBuilder();
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     */
    public networking.ProcessIdOrBuilder getProcessOrBuilder() {
      if (processBuilder_ != null) {
        return processBuilder_.getMessageOrBuilder();
      } else {
        return process_ == null ?
            networking.ProcessId.getDefaultInstance() : process_;
      }
    }
    /**
     * <code>.main.ProcessId process = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        networking.ProcessId, networking.ProcessId.Builder, networking.ProcessIdOrBuilder> 
        getProcessFieldBuilder() {
      if (processBuilder_ == null) {
        processBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            networking.ProcessId, networking.ProcessId.Builder, networking.ProcessIdOrBuilder>(
                getProcess(),
                getParentForChildren(),
                isClean());
        process_ = null;
      }
      return processBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:main.EpfdSuspect)
  }

  // @@protoc_insertion_point(class_scope:main.EpfdSuspect)
  private static final networking.EpfdSuspect DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new networking.EpfdSuspect();
  }

  public static networking.EpfdSuspect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EpfdSuspect>
      PARSER = new com.google.protobuf.AbstractParser<EpfdSuspect>() {
    @java.lang.Override
    public EpfdSuspect parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EpfdSuspect> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EpfdSuspect> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public networking.EpfdSuspect getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

