// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface EpInternalStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.EpInternalState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 valueTimestamp = 1;</code>
   * @return The valueTimestamp.
   */
  int getValueTimestamp();

  /**
   * <code>.main.Value value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.main.Value value = 2;</code>
   * @return The value.
   */
  networking.Value getValue();
  /**
   * <code>.main.Value value = 2;</code>
   */
  networking.ValueOrBuilder getValueOrBuilder();
}
