// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.main.Message.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.main.Message.Type type = 1;</code>
   * @return The type.
   */
  networking.Message.Type getType();

  /**
   * <code>string messageUuid = 2;</code>
   * @return The messageUuid.
   */
  java.lang.String getMessageUuid();
  /**
   * <code>string messageUuid = 2;</code>
   * @return The bytes for messageUuid.
   */
  com.google.protobuf.ByteString
      getMessageUuidBytes();

  /**
   * <pre>
   * Abstraction ID constructed as shown to the right of the system diagram
   * </pre>
   *
   * <code>string FromAbstractionId = 3;</code>
   * @return The fromAbstractionId.
   */
  java.lang.String getFromAbstractionId();
  /**
   * <pre>
   * Abstraction ID constructed as shown to the right of the system diagram
   * </pre>
   *
   * <code>string FromAbstractionId = 3;</code>
   * @return The bytes for fromAbstractionId.
   */
  com.google.protobuf.ByteString
      getFromAbstractionIdBytes();

  /**
   * <pre>
   * Abstraction ID constructed as shown to the right of the system diagram
   * </pre>
   *
   * <code>string ToAbstractionId = 4;</code>
   * @return The toAbstractionId.
   */
  java.lang.String getToAbstractionId();
  /**
   * <pre>
   * Abstraction ID constructed as shown to the right of the system diagram
   * </pre>
   *
   * <code>string ToAbstractionId = 4;</code>
   * @return The bytes for toAbstractionId.
   */
  com.google.protobuf.ByteString
      getToAbstractionIdBytes();

  /**
   * <code>string systemId = 5;</code>
   * @return The systemId.
   */
  java.lang.String getSystemId();
  /**
   * <code>string systemId = 5;</code>
   * @return The bytes for systemId.
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>.main.NetworkMessage networkMessage = 6;</code>
   * @return Whether the networkMessage field is set.
   */
  boolean hasNetworkMessage();
  /**
   * <code>.main.NetworkMessage networkMessage = 6;</code>
   * @return The networkMessage.
   */
  networking.NetworkMessage getNetworkMessage();
  /**
   * <code>.main.NetworkMessage networkMessage = 6;</code>
   */
  networking.NetworkMessageOrBuilder getNetworkMessageOrBuilder();

  /**
   * <code>.main.ProcRegistration procRegistration = 7;</code>
   * @return Whether the procRegistration field is set.
   */
  boolean hasProcRegistration();
  /**
   * <code>.main.ProcRegistration procRegistration = 7;</code>
   * @return The procRegistration.
   */
  networking.ProcRegistration getProcRegistration();
  /**
   * <code>.main.ProcRegistration procRegistration = 7;</code>
   */
  networking.ProcRegistrationOrBuilder getProcRegistrationOrBuilder();

  /**
   * <code>.main.ProcInitializeSystem procInitializeSystem = 8;</code>
   * @return Whether the procInitializeSystem field is set.
   */
  boolean hasProcInitializeSystem();
  /**
   * <code>.main.ProcInitializeSystem procInitializeSystem = 8;</code>
   * @return The procInitializeSystem.
   */
  networking.ProcInitializeSystem getProcInitializeSystem();
  /**
   * <code>.main.ProcInitializeSystem procInitializeSystem = 8;</code>
   */
  networking.ProcInitializeSystemOrBuilder getProcInitializeSystemOrBuilder();

  /**
   * <code>.main.ProcDestroySystem procDestroySystem = 9;</code>
   * @return Whether the procDestroySystem field is set.
   */
  boolean hasProcDestroySystem();
  /**
   * <code>.main.ProcDestroySystem procDestroySystem = 9;</code>
   * @return The procDestroySystem.
   */
  networking.ProcDestroySystem getProcDestroySystem();
  /**
   * <code>.main.ProcDestroySystem procDestroySystem = 9;</code>
   */
  networking.ProcDestroySystemOrBuilder getProcDestroySystemOrBuilder();

  /**
   * <code>.main.AppBroadcast appBroadcast = 10;</code>
   * @return Whether the appBroadcast field is set.
   */
  boolean hasAppBroadcast();
  /**
   * <code>.main.AppBroadcast appBroadcast = 10;</code>
   * @return The appBroadcast.
   */
  networking.AppBroadcast getAppBroadcast();
  /**
   * <code>.main.AppBroadcast appBroadcast = 10;</code>
   */
  networking.AppBroadcastOrBuilder getAppBroadcastOrBuilder();

  /**
   * <code>.main.AppValue appValue = 11;</code>
   * @return Whether the appValue field is set.
   */
  boolean hasAppValue();
  /**
   * <code>.main.AppValue appValue = 11;</code>
   * @return The appValue.
   */
  networking.AppValue getAppValue();
  /**
   * <code>.main.AppValue appValue = 11;</code>
   */
  networking.AppValueOrBuilder getAppValueOrBuilder();

  /**
   * <code>.main.AppPropose appPropose = 12;</code>
   * @return Whether the appPropose field is set.
   */
  boolean hasAppPropose();
  /**
   * <code>.main.AppPropose appPropose = 12;</code>
   * @return The appPropose.
   */
  networking.AppPropose getAppPropose();
  /**
   * <code>.main.AppPropose appPropose = 12;</code>
   */
  networking.AppProposeOrBuilder getAppProposeOrBuilder();

  /**
   * <code>.main.AppDecide appDecide = 13;</code>
   * @return Whether the appDecide field is set.
   */
  boolean hasAppDecide();
  /**
   * <code>.main.AppDecide appDecide = 13;</code>
   * @return The appDecide.
   */
  networking.AppDecide getAppDecide();
  /**
   * <code>.main.AppDecide appDecide = 13;</code>
   */
  networking.AppDecideOrBuilder getAppDecideOrBuilder();

  /**
   * <code>.main.AppRead appRead = 14;</code>
   * @return Whether the appRead field is set.
   */
  boolean hasAppRead();
  /**
   * <code>.main.AppRead appRead = 14;</code>
   * @return The appRead.
   */
  networking.AppRead getAppRead();
  /**
   * <code>.main.AppRead appRead = 14;</code>
   */
  networking.AppReadOrBuilder getAppReadOrBuilder();

  /**
   * <code>.main.AppWrite appWrite = 15;</code>
   * @return Whether the appWrite field is set.
   */
  boolean hasAppWrite();
  /**
   * <code>.main.AppWrite appWrite = 15;</code>
   * @return The appWrite.
   */
  networking.AppWrite getAppWrite();
  /**
   * <code>.main.AppWrite appWrite = 15;</code>
   */
  networking.AppWriteOrBuilder getAppWriteOrBuilder();

  /**
   * <code>.main.AppReadReturn appReadReturn = 16;</code>
   * @return Whether the appReadReturn field is set.
   */
  boolean hasAppReadReturn();
  /**
   * <code>.main.AppReadReturn appReadReturn = 16;</code>
   * @return The appReadReturn.
   */
  networking.AppReadReturn getAppReadReturn();
  /**
   * <code>.main.AppReadReturn appReadReturn = 16;</code>
   */
  networking.AppReadReturnOrBuilder getAppReadReturnOrBuilder();

  /**
   * <code>.main.AppWriteReturn appWriteReturn = 17;</code>
   * @return Whether the appWriteReturn field is set.
   */
  boolean hasAppWriteReturn();
  /**
   * <code>.main.AppWriteReturn appWriteReturn = 17;</code>
   * @return The appWriteReturn.
   */
  networking.AppWriteReturn getAppWriteReturn();
  /**
   * <code>.main.AppWriteReturn appWriteReturn = 17;</code>
   */
  networking.AppWriteReturnOrBuilder getAppWriteReturnOrBuilder();

  /**
   * <code>.main.UcDecide ucDecide = 20;</code>
   * @return Whether the ucDecide field is set.
   */
  boolean hasUcDecide();
  /**
   * <code>.main.UcDecide ucDecide = 20;</code>
   * @return The ucDecide.
   */
  networking.UcDecide getUcDecide();
  /**
   * <code>.main.UcDecide ucDecide = 20;</code>
   */
  networking.UcDecideOrBuilder getUcDecideOrBuilder();

  /**
   * <code>.main.UcPropose ucPropose = 21;</code>
   * @return Whether the ucPropose field is set.
   */
  boolean hasUcPropose();
  /**
   * <code>.main.UcPropose ucPropose = 21;</code>
   * @return The ucPropose.
   */
  networking.UcPropose getUcPropose();
  /**
   * <code>.main.UcPropose ucPropose = 21;</code>
   */
  networking.UcProposeOrBuilder getUcProposeOrBuilder();

  /**
   * <code>.main.EpAbort epAbort = 30;</code>
   * @return Whether the epAbort field is set.
   */
  boolean hasEpAbort();
  /**
   * <code>.main.EpAbort epAbort = 30;</code>
   * @return The epAbort.
   */
  networking.EpAbort getEpAbort();
  /**
   * <code>.main.EpAbort epAbort = 30;</code>
   */
  networking.EpAbortOrBuilder getEpAbortOrBuilder();

  /**
   * <code>.main.EpAborted epAborted = 31;</code>
   * @return Whether the epAborted field is set.
   */
  boolean hasEpAborted();
  /**
   * <code>.main.EpAborted epAborted = 31;</code>
   * @return The epAborted.
   */
  networking.EpAborted getEpAborted();
  /**
   * <code>.main.EpAborted epAborted = 31;</code>
   */
  networking.EpAbortedOrBuilder getEpAbortedOrBuilder();

  /**
   * <code>.main.EpInternalAccept epInternalAccept = 32;</code>
   * @return Whether the epInternalAccept field is set.
   */
  boolean hasEpInternalAccept();
  /**
   * <code>.main.EpInternalAccept epInternalAccept = 32;</code>
   * @return The epInternalAccept.
   */
  networking.EpInternalAccept getEpInternalAccept();
  /**
   * <code>.main.EpInternalAccept epInternalAccept = 32;</code>
   */
  networking.EpInternalAcceptOrBuilder getEpInternalAcceptOrBuilder();

  /**
   * <code>.main.EpDecide epDecide = 33;</code>
   * @return Whether the epDecide field is set.
   */
  boolean hasEpDecide();
  /**
   * <code>.main.EpDecide epDecide = 33;</code>
   * @return The epDecide.
   */
  networking.EpDecide getEpDecide();
  /**
   * <code>.main.EpDecide epDecide = 33;</code>
   */
  networking.EpDecideOrBuilder getEpDecideOrBuilder();

  /**
   * <code>.main.EpInternalDecided epInternalDecided = 34;</code>
   * @return Whether the epInternalDecided field is set.
   */
  boolean hasEpInternalDecided();
  /**
   * <code>.main.EpInternalDecided epInternalDecided = 34;</code>
   * @return The epInternalDecided.
   */
  networking.EpInternalDecided getEpInternalDecided();
  /**
   * <code>.main.EpInternalDecided epInternalDecided = 34;</code>
   */
  networking.EpInternalDecidedOrBuilder getEpInternalDecidedOrBuilder();

  /**
   * <code>.main.EpPropose epPropose = 35;</code>
   * @return Whether the epPropose field is set.
   */
  boolean hasEpPropose();
  /**
   * <code>.main.EpPropose epPropose = 35;</code>
   * @return The epPropose.
   */
  networking.EpPropose getEpPropose();
  /**
   * <code>.main.EpPropose epPropose = 35;</code>
   */
  networking.EpProposeOrBuilder getEpProposeOrBuilder();

  /**
   * <code>.main.EpInternalRead epInternalRead = 36;</code>
   * @return Whether the epInternalRead field is set.
   */
  boolean hasEpInternalRead();
  /**
   * <code>.main.EpInternalRead epInternalRead = 36;</code>
   * @return The epInternalRead.
   */
  networking.EpInternalRead getEpInternalRead();
  /**
   * <code>.main.EpInternalRead epInternalRead = 36;</code>
   */
  networking.EpInternalReadOrBuilder getEpInternalReadOrBuilder();

  /**
   * <code>.main.EpInternalState epInternalState = 37;</code>
   * @return Whether the epInternalState field is set.
   */
  boolean hasEpInternalState();
  /**
   * <code>.main.EpInternalState epInternalState = 37;</code>
   * @return The epInternalState.
   */
  networking.EpInternalState getEpInternalState();
  /**
   * <code>.main.EpInternalState epInternalState = 37;</code>
   */
  networking.EpInternalStateOrBuilder getEpInternalStateOrBuilder();

  /**
   * <code>.main.EpInternalWrite epInternalWrite = 38;</code>
   * @return Whether the epInternalWrite field is set.
   */
  boolean hasEpInternalWrite();
  /**
   * <code>.main.EpInternalWrite epInternalWrite = 38;</code>
   * @return The epInternalWrite.
   */
  networking.EpInternalWrite getEpInternalWrite();
  /**
   * <code>.main.EpInternalWrite epInternalWrite = 38;</code>
   */
  networking.EpInternalWriteOrBuilder getEpInternalWriteOrBuilder();

  /**
   * <code>.main.EcInternalNack ecInternalNack = 41;</code>
   * @return Whether the ecInternalNack field is set.
   */
  boolean hasEcInternalNack();
  /**
   * <code>.main.EcInternalNack ecInternalNack = 41;</code>
   * @return The ecInternalNack.
   */
  networking.EcInternalNack getEcInternalNack();
  /**
   * <code>.main.EcInternalNack ecInternalNack = 41;</code>
   */
  networking.EcInternalNackOrBuilder getEcInternalNackOrBuilder();

  /**
   * <code>.main.EcInternalNewEpoch ecInternalNewEpoch = 42;</code>
   * @return Whether the ecInternalNewEpoch field is set.
   */
  boolean hasEcInternalNewEpoch();
  /**
   * <code>.main.EcInternalNewEpoch ecInternalNewEpoch = 42;</code>
   * @return The ecInternalNewEpoch.
   */
  networking.EcInternalNewEpoch getEcInternalNewEpoch();
  /**
   * <code>.main.EcInternalNewEpoch ecInternalNewEpoch = 42;</code>
   */
  networking.EcInternalNewEpochOrBuilder getEcInternalNewEpochOrBuilder();

  /**
   * <code>.main.EcStartEpoch ecStartEpoch = 43;</code>
   * @return Whether the ecStartEpoch field is set.
   */
  boolean hasEcStartEpoch();
  /**
   * <code>.main.EcStartEpoch ecStartEpoch = 43;</code>
   * @return The ecStartEpoch.
   */
  networking.EcStartEpoch getEcStartEpoch();
  /**
   * <code>.main.EcStartEpoch ecStartEpoch = 43;</code>
   */
  networking.EcStartEpochOrBuilder getEcStartEpochOrBuilder();

  /**
   * <code>.main.BebBroadcast bebBroadcast = 50;</code>
   * @return Whether the bebBroadcast field is set.
   */
  boolean hasBebBroadcast();
  /**
   * <code>.main.BebBroadcast bebBroadcast = 50;</code>
   * @return The bebBroadcast.
   */
  networking.BebBroadcast getBebBroadcast();
  /**
   * <code>.main.BebBroadcast bebBroadcast = 50;</code>
   */
  networking.BebBroadcastOrBuilder getBebBroadcastOrBuilder();

  /**
   * <code>.main.BebDeliver bebDeliver = 51;</code>
   * @return Whether the bebDeliver field is set.
   */
  boolean hasBebDeliver();
  /**
   * <code>.main.BebDeliver bebDeliver = 51;</code>
   * @return The bebDeliver.
   */
  networking.BebDeliver getBebDeliver();
  /**
   * <code>.main.BebDeliver bebDeliver = 51;</code>
   */
  networking.BebDeliverOrBuilder getBebDeliverOrBuilder();

  /**
   * <code>.main.EldTimeout eldTimeout = 60;</code>
   * @return Whether the eldTimeout field is set.
   */
  boolean hasEldTimeout();
  /**
   * <code>.main.EldTimeout eldTimeout = 60;</code>
   * @return The eldTimeout.
   */
  networking.EldTimeout getEldTimeout();
  /**
   * <code>.main.EldTimeout eldTimeout = 60;</code>
   */
  networking.EldTimeoutOrBuilder getEldTimeoutOrBuilder();

  /**
   * <code>.main.EldTrust eldTrust = 61;</code>
   * @return Whether the eldTrust field is set.
   */
  boolean hasEldTrust();
  /**
   * <code>.main.EldTrust eldTrust = 61;</code>
   * @return The eldTrust.
   */
  networking.EldTrust getEldTrust();
  /**
   * <code>.main.EldTrust eldTrust = 61;</code>
   */
  networking.EldTrustOrBuilder getEldTrustOrBuilder();

  /**
   * <code>.main.NnarInternalAck nnarInternalAck = 70;</code>
   * @return Whether the nnarInternalAck field is set.
   */
  boolean hasNnarInternalAck();
  /**
   * <code>.main.NnarInternalAck nnarInternalAck = 70;</code>
   * @return The nnarInternalAck.
   */
  networking.NnarInternalAck getNnarInternalAck();
  /**
   * <code>.main.NnarInternalAck nnarInternalAck = 70;</code>
   */
  networking.NnarInternalAckOrBuilder getNnarInternalAckOrBuilder();

  /**
   * <code>.main.NnarInternalRead nnarInternalRead = 71;</code>
   * @return Whether the nnarInternalRead field is set.
   */
  boolean hasNnarInternalRead();
  /**
   * <code>.main.NnarInternalRead nnarInternalRead = 71;</code>
   * @return The nnarInternalRead.
   */
  networking.NnarInternalRead getNnarInternalRead();
  /**
   * <code>.main.NnarInternalRead nnarInternalRead = 71;</code>
   */
  networking.NnarInternalReadOrBuilder getNnarInternalReadOrBuilder();

  /**
   * <code>.main.NnarInternalValue nnarInternalValue = 72;</code>
   * @return Whether the nnarInternalValue field is set.
   */
  boolean hasNnarInternalValue();
  /**
   * <code>.main.NnarInternalValue nnarInternalValue = 72;</code>
   * @return The nnarInternalValue.
   */
  networking.NnarInternalValue getNnarInternalValue();
  /**
   * <code>.main.NnarInternalValue nnarInternalValue = 72;</code>
   */
  networking.NnarInternalValueOrBuilder getNnarInternalValueOrBuilder();

  /**
   * <code>.main.NnarInternalWrite nnarInternalWrite = 73;</code>
   * @return Whether the nnarInternalWrite field is set.
   */
  boolean hasNnarInternalWrite();
  /**
   * <code>.main.NnarInternalWrite nnarInternalWrite = 73;</code>
   * @return The nnarInternalWrite.
   */
  networking.NnarInternalWrite getNnarInternalWrite();
  /**
   * <code>.main.NnarInternalWrite nnarInternalWrite = 73;</code>
   */
  networking.NnarInternalWriteOrBuilder getNnarInternalWriteOrBuilder();

  /**
   * <code>.main.NnarRead nnarRead = 74;</code>
   * @return Whether the nnarRead field is set.
   */
  boolean hasNnarRead();
  /**
   * <code>.main.NnarRead nnarRead = 74;</code>
   * @return The nnarRead.
   */
  networking.NnarRead getNnarRead();
  /**
   * <code>.main.NnarRead nnarRead = 74;</code>
   */
  networking.NnarReadOrBuilder getNnarReadOrBuilder();

  /**
   * <code>.main.NnarReadReturn nnarReadReturn = 75;</code>
   * @return Whether the nnarReadReturn field is set.
   */
  boolean hasNnarReadReturn();
  /**
   * <code>.main.NnarReadReturn nnarReadReturn = 75;</code>
   * @return The nnarReadReturn.
   */
  networking.NnarReadReturn getNnarReadReturn();
  /**
   * <code>.main.NnarReadReturn nnarReadReturn = 75;</code>
   */
  networking.NnarReadReturnOrBuilder getNnarReadReturnOrBuilder();

  /**
   * <code>.main.NnarWrite nnarWrite = 76;</code>
   * @return Whether the nnarWrite field is set.
   */
  boolean hasNnarWrite();
  /**
   * <code>.main.NnarWrite nnarWrite = 76;</code>
   * @return The nnarWrite.
   */
  networking.NnarWrite getNnarWrite();
  /**
   * <code>.main.NnarWrite nnarWrite = 76;</code>
   */
  networking.NnarWriteOrBuilder getNnarWriteOrBuilder();

  /**
   * <code>.main.NnarWriteReturn nnarWriteReturn = 77;</code>
   * @return Whether the nnarWriteReturn field is set.
   */
  boolean hasNnarWriteReturn();
  /**
   * <code>.main.NnarWriteReturn nnarWriteReturn = 77;</code>
   * @return The nnarWriteReturn.
   */
  networking.NnarWriteReturn getNnarWriteReturn();
  /**
   * <code>.main.NnarWriteReturn nnarWriteReturn = 77;</code>
   */
  networking.NnarWriteReturnOrBuilder getNnarWriteReturnOrBuilder();

  /**
   * <code>.main.EpfdTimeout epfdTimeout = 80;</code>
   * @return Whether the epfdTimeout field is set.
   */
  boolean hasEpfdTimeout();
  /**
   * <code>.main.EpfdTimeout epfdTimeout = 80;</code>
   * @return The epfdTimeout.
   */
  networking.EpfdTimeout getEpfdTimeout();
  /**
   * <code>.main.EpfdTimeout epfdTimeout = 80;</code>
   */
  networking.EpfdTimeoutOrBuilder getEpfdTimeoutOrBuilder();

  /**
   * <code>.main.EpfdInternalHeartbeatRequest epfdInternalHeartbeatRequest = 81;</code>
   * @return Whether the epfdInternalHeartbeatRequest field is set.
   */
  boolean hasEpfdInternalHeartbeatRequest();
  /**
   * <code>.main.EpfdInternalHeartbeatRequest epfdInternalHeartbeatRequest = 81;</code>
   * @return The epfdInternalHeartbeatRequest.
   */
  networking.EpfdInternalHeartbeatRequest getEpfdInternalHeartbeatRequest();
  /**
   * <code>.main.EpfdInternalHeartbeatRequest epfdInternalHeartbeatRequest = 81;</code>
   */
  networking.EpfdInternalHeartbeatRequestOrBuilder getEpfdInternalHeartbeatRequestOrBuilder();

  /**
   * <code>.main.EpfdInternalHeartbeatReply epfdInternalHeartbeatReply = 82;</code>
   * @return Whether the epfdInternalHeartbeatReply field is set.
   */
  boolean hasEpfdInternalHeartbeatReply();
  /**
   * <code>.main.EpfdInternalHeartbeatReply epfdInternalHeartbeatReply = 82;</code>
   * @return The epfdInternalHeartbeatReply.
   */
  networking.EpfdInternalHeartbeatReply getEpfdInternalHeartbeatReply();
  /**
   * <code>.main.EpfdInternalHeartbeatReply epfdInternalHeartbeatReply = 82;</code>
   */
  networking.EpfdInternalHeartbeatReplyOrBuilder getEpfdInternalHeartbeatReplyOrBuilder();

  /**
   * <code>.main.EpfdSuspect epfdSuspect = 83;</code>
   * @return Whether the epfdSuspect field is set.
   */
  boolean hasEpfdSuspect();
  /**
   * <code>.main.EpfdSuspect epfdSuspect = 83;</code>
   * @return The epfdSuspect.
   */
  networking.EpfdSuspect getEpfdSuspect();
  /**
   * <code>.main.EpfdSuspect epfdSuspect = 83;</code>
   */
  networking.EpfdSuspectOrBuilder getEpfdSuspectOrBuilder();

  /**
   * <code>.main.EpfdRestore epfdRestore = 84;</code>
   * @return Whether the epfdRestore field is set.
   */
  boolean hasEpfdRestore();
  /**
   * <code>.main.EpfdRestore epfdRestore = 84;</code>
   * @return The epfdRestore.
   */
  networking.EpfdRestore getEpfdRestore();
  /**
   * <code>.main.EpfdRestore epfdRestore = 84;</code>
   */
  networking.EpfdRestoreOrBuilder getEpfdRestoreOrBuilder();

  /**
   * <code>.main.PlDeliver plDeliver = 90;</code>
   * @return Whether the plDeliver field is set.
   */
  boolean hasPlDeliver();
  /**
   * <code>.main.PlDeliver plDeliver = 90;</code>
   * @return The plDeliver.
   */
  networking.PlDeliver getPlDeliver();
  /**
   * <code>.main.PlDeliver plDeliver = 90;</code>
   */
  networking.PlDeliverOrBuilder getPlDeliverOrBuilder();

  /**
   * <code>.main.PlSend plSend = 91;</code>
   * @return Whether the plSend field is set.
   */
  boolean hasPlSend();
  /**
   * <code>.main.PlSend plSend = 91;</code>
   * @return The plSend.
   */
  networking.PlSend getPlSend();
  /**
   * <code>.main.PlSend plSend = 91;</code>
   */
  networking.PlSendOrBuilder getPlSendOrBuilder();
}
