// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface NetworkMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.NetworkMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string senderHost = 1;</code>
   * @return The senderHost.
   */
  java.lang.String getSenderHost();
  /**
   * <code>string senderHost = 1;</code>
   * @return The bytes for senderHost.
   */
  com.google.protobuf.ByteString
      getSenderHostBytes();

  /**
   * <code>int32 senderListeningPort = 2;</code>
   * @return The senderListeningPort.
   */
  int getSenderListeningPort();

  /**
   * <code>.main.Message message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.main.Message message = 3;</code>
   * @return The message.
   */
  networking.Message getMessage();
  /**
   * <code>.main.Message message = 3;</code>
   */
  networking.MessageOrBuilder getMessageOrBuilder();
}
