// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

/**
 * <pre>
 * Network-traveling message
 * When handling MessageA(PlSend(MessageB)) create MessageC(NetworkMessage(MessageB)), setting:
 * MessageC.SystemId = MessageA.SystemId
 * MessageC.ToAbstractionId = MessageA.ToAbstractionId
 * NetworkMessage.senderHost = N/A (ignore)
 * NetworkMessage.senderListeningPort = The your listening port
 * Then marshal MessageC to byte buffer and send:
 * bytes 0 - 3: buffer length
 * bytes 4 -  : buffer data
 * When unmarshalling from a buffer received from the network create MessageD(PlDeliver(MessageB)), setting:
 * MessageD.ToAbstractionId = MessageC.ToAbstractionId
 * </pre>
 *
 * Protobuf type {@code main.NetworkMessage}
 */
public final class NetworkMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:main.NetworkMessage)
    NetworkMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      NetworkMessage.class.getName());
  }
  // Use NetworkMessage.newBuilder() to construct.
  private NetworkMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NetworkMessage() {
    senderHost_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return networking.CommunicationProtocol.internal_static_main_NetworkMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return networking.CommunicationProtocol.internal_static_main_NetworkMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            networking.NetworkMessage.class, networking.NetworkMessage.Builder.class);
  }

  private int bitField0_;
  public static final int SENDERHOST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object senderHost_ = "";
  /**
   * <code>string senderHost = 1;</code>
   * @return The senderHost.
   */
  @java.lang.Override
  public java.lang.String getSenderHost() {
    java.lang.Object ref = senderHost_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderHost_ = s;
      return s;
    }
  }
  /**
   * <code>string senderHost = 1;</code>
   * @return The bytes for senderHost.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderHostBytes() {
    java.lang.Object ref = senderHost_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDERLISTENINGPORT_FIELD_NUMBER = 2;
  private int senderListeningPort_ = 0;
  /**
   * <code>int32 senderListeningPort = 2;</code>
   * @return The senderListeningPort.
   */
  @java.lang.Override
  public int getSenderListeningPort() {
    return senderListeningPort_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private networking.Message message_;
  /**
   * <code>.main.Message message = 3;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.main.Message message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public networking.Message getMessage() {
    return message_ == null ? networking.Message.getDefaultInstance() : message_;
  }
  /**
   * <code>.main.Message message = 3;</code>
   */
  @java.lang.Override
  public networking.MessageOrBuilder getMessageOrBuilder() {
    return message_ == null ? networking.Message.getDefaultInstance() : message_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderHost_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, senderHost_);
    }
    if (senderListeningPort_ != 0) {
      output.writeInt32(2, senderListeningPort_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getMessage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderHost_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, senderHost_);
    }
    if (senderListeningPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, senderListeningPort_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMessage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof networking.NetworkMessage)) {
      return super.equals(obj);
    }
    networking.NetworkMessage other = (networking.NetworkMessage) obj;

    if (!getSenderHost()
        .equals(other.getSenderHost())) return false;
    if (getSenderListeningPort()
        != other.getSenderListeningPort()) return false;
    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDERHOST_FIELD_NUMBER;
    hash = (53 * hash) + getSenderHost().hashCode();
    hash = (37 * hash) + SENDERLISTENINGPORT_FIELD_NUMBER;
    hash = (53 * hash) + getSenderListeningPort();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static networking.NetworkMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.NetworkMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.NetworkMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.NetworkMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.NetworkMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.NetworkMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.NetworkMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.NetworkMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static networking.NetworkMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static networking.NetworkMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static networking.NetworkMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.NetworkMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(networking.NetworkMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Network-traveling message
   * When handling MessageA(PlSend(MessageB)) create MessageC(NetworkMessage(MessageB)), setting:
   * MessageC.SystemId = MessageA.SystemId
   * MessageC.ToAbstractionId = MessageA.ToAbstractionId
   * NetworkMessage.senderHost = N/A (ignore)
   * NetworkMessage.senderListeningPort = The your listening port
   * Then marshal MessageC to byte buffer and send:
   * bytes 0 - 3: buffer length
   * bytes 4 -  : buffer data
   * When unmarshalling from a buffer received from the network create MessageD(PlDeliver(MessageB)), setting:
   * MessageD.ToAbstractionId = MessageC.ToAbstractionId
   * </pre>
   *
   * Protobuf type {@code main.NetworkMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:main.NetworkMessage)
      networking.NetworkMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return networking.CommunicationProtocol.internal_static_main_NetworkMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return networking.CommunicationProtocol.internal_static_main_NetworkMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              networking.NetworkMessage.class, networking.NetworkMessage.Builder.class);
    }

    // Construct using networking.NetworkMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      senderHost_ = "";
      senderListeningPort_ = 0;
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return networking.CommunicationProtocol.internal_static_main_NetworkMessage_descriptor;
    }

    @java.lang.Override
    public networking.NetworkMessage getDefaultInstanceForType() {
      return networking.NetworkMessage.getDefaultInstance();
    }

    @java.lang.Override
    public networking.NetworkMessage build() {
      networking.NetworkMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public networking.NetworkMessage buildPartial() {
      networking.NetworkMessage result = new networking.NetworkMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(networking.NetworkMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.senderHost_ = senderHost_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.senderListeningPort_ = senderListeningPort_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.message_ = messageBuilder_ == null
            ? message_
            : messageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof networking.NetworkMessage) {
        return mergeFrom((networking.NetworkMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(networking.NetworkMessage other) {
      if (other == networking.NetworkMessage.getDefaultInstance()) return this;
      if (!other.getSenderHost().isEmpty()) {
        senderHost_ = other.senderHost_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSenderListeningPort() != 0) {
        setSenderListeningPort(other.getSenderListeningPort());
      }
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              senderHost_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              senderListeningPort_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object senderHost_ = "";
    /**
     * <code>string senderHost = 1;</code>
     * @return The senderHost.
     */
    public java.lang.String getSenderHost() {
      java.lang.Object ref = senderHost_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderHost_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string senderHost = 1;</code>
     * @return The bytes for senderHost.
     */
    public com.google.protobuf.ByteString
        getSenderHostBytes() {
      java.lang.Object ref = senderHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string senderHost = 1;</code>
     * @param value The senderHost to set.
     * @return This builder for chaining.
     */
    public Builder setSenderHost(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      senderHost_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string senderHost = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderHost() {
      senderHost_ = getDefaultInstance().getSenderHost();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string senderHost = 1;</code>
     * @param value The bytes for senderHost to set.
     * @return This builder for chaining.
     */
    public Builder setSenderHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      senderHost_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int senderListeningPort_ ;
    /**
     * <code>int32 senderListeningPort = 2;</code>
     * @return The senderListeningPort.
     */
    @java.lang.Override
    public int getSenderListeningPort() {
      return senderListeningPort_;
    }
    /**
     * <code>int32 senderListeningPort = 2;</code>
     * @param value The senderListeningPort to set.
     * @return This builder for chaining.
     */
    public Builder setSenderListeningPort(int value) {

      senderListeningPort_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 senderListeningPort = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderListeningPort() {
      bitField0_ = (bitField0_ & ~0x00000002);
      senderListeningPort_ = 0;
      onChanged();
      return this;
    }

    private networking.Message message_;
    private com.google.protobuf.SingleFieldBuilder<
        networking.Message, networking.Message.Builder, networking.MessageOrBuilder> messageBuilder_;
    /**
     * <code>.main.Message message = 3;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.main.Message message = 3;</code>
     * @return The message.
     */
    public networking.Message getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? networking.Message.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.main.Message message = 3;</code>
     */
    public Builder setMessage(networking.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
      } else {
        messageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.main.Message message = 3;</code>
     */
    public Builder setMessage(
        networking.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.main.Message message = 3;</code>
     */
    public Builder mergeMessage(networking.Message value) {
      if (messageBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          message_ != null &&
          message_ != networking.Message.getDefaultInstance()) {
          getMessageBuilder().mergeFrom(value);
        } else {
          message_ = value;
        }
      } else {
        messageBuilder_.mergeFrom(value);
      }
      if (message_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.main.Message message = 3;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.main.Message message = 3;</code>
     */
    public networking.Message.Builder getMessageBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.main.Message message = 3;</code>
     */
    public networking.MessageOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            networking.Message.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.main.Message message = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        networking.Message, networking.Message.Builder, networking.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            networking.Message, networking.Message.Builder, networking.MessageOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:main.NetworkMessage)
  }

  // @@protoc_insertion_point(class_scope:main.NetworkMessage)
  private static final networking.NetworkMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new networking.NetworkMessage();
  }

  public static networking.NetworkMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetworkMessage>
      PARSER = new com.google.protobuf.AbstractParser<NetworkMessage>() {
    @java.lang.Override
    public NetworkMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NetworkMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetworkMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public networking.NetworkMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

