// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface NnarInternalAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.NnarInternalAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 readId = 1;</code>
   * @return The readId.
   */
  int getReadId();
}
