// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface NnarInternalValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.NnarInternalValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 readId = 1;</code>
   * @return The readId.
   */
  int getReadId();

  /**
   * <code>int32 timestamp = 2;</code>
   * @return The timestamp.
   */
  int getTimestamp();

  /**
   * <code>int32 writerRank = 3;</code>
   * @return The writerRank.
   */
  int getWriterRank();

  /**
   * <code>.main.Value value = 4;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.main.Value value = 4;</code>
   * @return The value.
   */
  networking.Value getValue();
  /**
   * <code>.main.Value value = 4;</code>
   */
  networking.ValueOrBuilder getValueOrBuilder();
}
