// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

/**
 * Protobuf type {@code main.NnarInternalWrite}
 */
public final class NnarInternalWrite extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:main.NnarInternalWrite)
    NnarInternalWriteOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      NnarInternalWrite.class.getName());
  }
  // Use NnarInternalWrite.newBuilder() to construct.
  private NnarInternalWrite(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NnarInternalWrite() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return networking.CommunicationProtocol.internal_static_main_NnarInternalWrite_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return networking.CommunicationProtocol.internal_static_main_NnarInternalWrite_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            networking.NnarInternalWrite.class, networking.NnarInternalWrite.Builder.class);
  }

  private int bitField0_;
  public static final int READID_FIELD_NUMBER = 1;
  private int readId_ = 0;
  /**
   * <code>int32 readId = 1;</code>
   * @return The readId.
   */
  @java.lang.Override
  public int getReadId() {
    return readId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private int timestamp_ = 0;
  /**
   * <code>int32 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public int getTimestamp() {
    return timestamp_;
  }

  public static final int WRITERRANK_FIELD_NUMBER = 3;
  private int writerRank_ = 0;
  /**
   * <code>int32 writerRank = 3;</code>
   * @return The writerRank.
   */
  @java.lang.Override
  public int getWriterRank() {
    return writerRank_;
  }

  public static final int VALUE_FIELD_NUMBER = 4;
  private networking.Value value_;
  /**
   * <code>.main.Value value = 4;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.main.Value value = 4;</code>
   * @return The value.
   */
  @java.lang.Override
  public networking.Value getValue() {
    return value_ == null ? networking.Value.getDefaultInstance() : value_;
  }
  /**
   * <code>.main.Value value = 4;</code>
   */
  @java.lang.Override
  public networking.ValueOrBuilder getValueOrBuilder() {
    return value_ == null ? networking.Value.getDefaultInstance() : value_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (readId_ != 0) {
      output.writeInt32(1, readId_);
    }
    if (timestamp_ != 0) {
      output.writeInt32(2, timestamp_);
    }
    if (writerRank_ != 0) {
      output.writeInt32(3, writerRank_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getValue());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (readId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, readId_);
    }
    if (timestamp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timestamp_);
    }
    if (writerRank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, writerRank_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getValue());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof networking.NnarInternalWrite)) {
      return super.equals(obj);
    }
    networking.NnarInternalWrite other = (networking.NnarInternalWrite) obj;

    if (getReadId()
        != other.getReadId()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getWriterRank()
        != other.getWriterRank()) return false;
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + READID_FIELD_NUMBER;
    hash = (53 * hash) + getReadId();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp();
    hash = (37 * hash) + WRITERRANK_FIELD_NUMBER;
    hash = (53 * hash) + getWriterRank();
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static networking.NnarInternalWrite parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.NnarInternalWrite parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.NnarInternalWrite parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.NnarInternalWrite parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.NnarInternalWrite parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.NnarInternalWrite parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.NnarInternalWrite parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.NnarInternalWrite parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static networking.NnarInternalWrite parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static networking.NnarInternalWrite parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static networking.NnarInternalWrite parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.NnarInternalWrite parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(networking.NnarInternalWrite prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code main.NnarInternalWrite}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:main.NnarInternalWrite)
      networking.NnarInternalWriteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return networking.CommunicationProtocol.internal_static_main_NnarInternalWrite_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return networking.CommunicationProtocol.internal_static_main_NnarInternalWrite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              networking.NnarInternalWrite.class, networking.NnarInternalWrite.Builder.class);
    }

    // Construct using networking.NnarInternalWrite.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getValueFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      readId_ = 0;
      timestamp_ = 0;
      writerRank_ = 0;
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return networking.CommunicationProtocol.internal_static_main_NnarInternalWrite_descriptor;
    }

    @java.lang.Override
    public networking.NnarInternalWrite getDefaultInstanceForType() {
      return networking.NnarInternalWrite.getDefaultInstance();
    }

    @java.lang.Override
    public networking.NnarInternalWrite build() {
      networking.NnarInternalWrite result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public networking.NnarInternalWrite buildPartial() {
      networking.NnarInternalWrite result = new networking.NnarInternalWrite(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(networking.NnarInternalWrite result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.readId_ = readId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.writerRank_ = writerRank_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.value_ = valueBuilder_ == null
            ? value_
            : valueBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof networking.NnarInternalWrite) {
        return mergeFrom((networking.NnarInternalWrite)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(networking.NnarInternalWrite other) {
      if (other == networking.NnarInternalWrite.getDefaultInstance()) return this;
      if (other.getReadId() != 0) {
        setReadId(other.getReadId());
      }
      if (other.getTimestamp() != 0) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getWriterRank() != 0) {
        setWriterRank(other.getWriterRank());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              readId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              timestamp_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              writerRank_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int readId_ ;
    /**
     * <code>int32 readId = 1;</code>
     * @return The readId.
     */
    @java.lang.Override
    public int getReadId() {
      return readId_;
    }
    /**
     * <code>int32 readId = 1;</code>
     * @param value The readId to set.
     * @return This builder for chaining.
     */
    public Builder setReadId(int value) {

      readId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 readId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      readId_ = 0;
      onChanged();
      return this;
    }

    private int timestamp_ ;
    /**
     * <code>int32 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int32 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(int value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0;
      onChanged();
      return this;
    }

    private int writerRank_ ;
    /**
     * <code>int32 writerRank = 3;</code>
     * @return The writerRank.
     */
    @java.lang.Override
    public int getWriterRank() {
      return writerRank_;
    }
    /**
     * <code>int32 writerRank = 3;</code>
     * @param value The writerRank to set.
     * @return This builder for chaining.
     */
    public Builder setWriterRank(int value) {

      writerRank_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 writerRank = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWriterRank() {
      bitField0_ = (bitField0_ & ~0x00000004);
      writerRank_ = 0;
      onChanged();
      return this;
    }

    private networking.Value value_;
    private com.google.protobuf.SingleFieldBuilder<
        networking.Value, networking.Value.Builder, networking.ValueOrBuilder> valueBuilder_;
    /**
     * <code>.main.Value value = 4;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.main.Value value = 4;</code>
     * @return The value.
     */
    public networking.Value getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? networking.Value.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.main.Value value = 4;</code>
     */
    public Builder setValue(networking.Value value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
      } else {
        valueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.main.Value value = 4;</code>
     */
    public Builder setValue(
        networking.Value.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.main.Value value = 4;</code>
     */
    public Builder mergeValue(networking.Value value) {
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          value_ != null &&
          value_ != networking.Value.getDefaultInstance()) {
          getValueBuilder().mergeFrom(value);
        } else {
          value_ = value;
        }
      } else {
        valueBuilder_.mergeFrom(value);
      }
      if (value_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.main.Value value = 4;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000008);
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.main.Value value = 4;</code>
     */
    public networking.Value.Builder getValueBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.main.Value value = 4;</code>
     */
    public networking.ValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            networking.Value.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.main.Value value = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        networking.Value, networking.Value.Builder, networking.ValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            networking.Value, networking.Value.Builder, networking.ValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:main.NnarInternalWrite)
  }

  // @@protoc_insertion_point(class_scope:main.NnarInternalWrite)
  private static final networking.NnarInternalWrite DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new networking.NnarInternalWrite();
  }

  public static networking.NnarInternalWrite getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NnarInternalWrite>
      PARSER = new com.google.protobuf.AbstractParser<NnarInternalWrite>() {
    @java.lang.Override
    public NnarInternalWrite parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NnarInternalWrite> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NnarInternalWrite> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public networking.NnarInternalWrite getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

