// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface PlDeliverOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.PlDeliver)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.main.ProcessId sender = 1;</code>
   * @return Whether the sender field is set.
   */
  boolean hasSender();
  /**
   * <code>.main.ProcessId sender = 1;</code>
   * @return The sender.
   */
  networking.ProcessId getSender();
  /**
   * <code>.main.ProcessId sender = 1;</code>
   */
  networking.ProcessIdOrBuilder getSenderOrBuilder();

  /**
   * <code>.main.Message message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.main.Message message = 2;</code>
   * @return The message.
   */
  networking.Message getMessage();
  /**
   * <code>.main.Message message = 2;</code>
   */
  networking.MessageOrBuilder getMessageOrBuilder();
}
