// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface PlSendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.PlSend)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.main.ProcessId destination = 1;</code>
   * @return Whether the destination field is set.
   */
  boolean hasDestination();
  /**
   * <code>.main.ProcessId destination = 1;</code>
   * @return The destination.
   */
  networking.ProcessId getDestination();
  /**
   * <code>.main.ProcessId destination = 1;</code>
   */
  networking.ProcessIdOrBuilder getDestinationOrBuilder();

  /**
   * <code>.main.Message message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.main.Message message = 2;</code>
   * @return The message.
   */
  networking.Message getMessage();
  /**
   * <code>.main.Message message = 2;</code>
   */
  networking.MessageOrBuilder getMessageOrBuilder();
}
