// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

/**
 * <pre>
 * Received from the HUB as Message(NetworkMessage(Message(AppInitializeSystem))). Should
 * </pre>
 *
 * Protobuf type {@code main.ProcInitializeSystem}
 */
public final class ProcInitializeSystem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:main.ProcInitializeSystem)
    ProcInitializeSystemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      ProcInitializeSystem.class.getName());
  }
  // Use ProcInitializeSystem.newBuilder() to construct.
  private ProcInitializeSystem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProcInitializeSystem() {
    processes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return networking.CommunicationProtocol.internal_static_main_ProcInitializeSystem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return networking.CommunicationProtocol.internal_static_main_ProcInitializeSystem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            networking.ProcInitializeSystem.class, networking.ProcInitializeSystem.Builder.class);
  }

  public static final int PROCESSES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<networking.ProcessId> processes_;
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<networking.ProcessId> getProcessesList() {
    return processes_;
  }
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends networking.ProcessIdOrBuilder> 
      getProcessesOrBuilderList() {
    return processes_;
  }
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  @java.lang.Override
  public int getProcessesCount() {
    return processes_.size();
  }
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  @java.lang.Override
  public networking.ProcessId getProcesses(int index) {
    return processes_.get(index);
  }
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  @java.lang.Override
  public networking.ProcessIdOrBuilder getProcessesOrBuilder(
      int index) {
    return processes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < processes_.size(); i++) {
      output.writeMessage(1, processes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < processes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, processes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof networking.ProcInitializeSystem)) {
      return super.equals(obj);
    }
    networking.ProcInitializeSystem other = (networking.ProcInitializeSystem) obj;

    if (!getProcessesList()
        .equals(other.getProcessesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProcessesCount() > 0) {
      hash = (37 * hash) + PROCESSES_FIELD_NUMBER;
      hash = (53 * hash) + getProcessesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static networking.ProcInitializeSystem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.ProcInitializeSystem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.ProcInitializeSystem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.ProcInitializeSystem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.ProcInitializeSystem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static networking.ProcInitializeSystem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static networking.ProcInitializeSystem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.ProcInitializeSystem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static networking.ProcInitializeSystem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static networking.ProcInitializeSystem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static networking.ProcInitializeSystem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static networking.ProcInitializeSystem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(networking.ProcInitializeSystem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Received from the HUB as Message(NetworkMessage(Message(AppInitializeSystem))). Should
   * </pre>
   *
   * Protobuf type {@code main.ProcInitializeSystem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:main.ProcInitializeSystem)
      networking.ProcInitializeSystemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return networking.CommunicationProtocol.internal_static_main_ProcInitializeSystem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return networking.CommunicationProtocol.internal_static_main_ProcInitializeSystem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              networking.ProcInitializeSystem.class, networking.ProcInitializeSystem.Builder.class);
    }

    // Construct using networking.ProcInitializeSystem.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (processesBuilder_ == null) {
        processes_ = java.util.Collections.emptyList();
      } else {
        processes_ = null;
        processesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return networking.CommunicationProtocol.internal_static_main_ProcInitializeSystem_descriptor;
    }

    @java.lang.Override
    public networking.ProcInitializeSystem getDefaultInstanceForType() {
      return networking.ProcInitializeSystem.getDefaultInstance();
    }

    @java.lang.Override
    public networking.ProcInitializeSystem build() {
      networking.ProcInitializeSystem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public networking.ProcInitializeSystem buildPartial() {
      networking.ProcInitializeSystem result = new networking.ProcInitializeSystem(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(networking.ProcInitializeSystem result) {
      if (processesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          processes_ = java.util.Collections.unmodifiableList(processes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.processes_ = processes_;
      } else {
        result.processes_ = processesBuilder_.build();
      }
    }

    private void buildPartial0(networking.ProcInitializeSystem result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof networking.ProcInitializeSystem) {
        return mergeFrom((networking.ProcInitializeSystem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(networking.ProcInitializeSystem other) {
      if (other == networking.ProcInitializeSystem.getDefaultInstance()) return this;
      if (processesBuilder_ == null) {
        if (!other.processes_.isEmpty()) {
          if (processes_.isEmpty()) {
            processes_ = other.processes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProcessesIsMutable();
            processes_.addAll(other.processes_);
          }
          onChanged();
        }
      } else {
        if (!other.processes_.isEmpty()) {
          if (processesBuilder_.isEmpty()) {
            processesBuilder_.dispose();
            processesBuilder_ = null;
            processes_ = other.processes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            processesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getProcessesFieldBuilder() : null;
          } else {
            processesBuilder_.addAllMessages(other.processes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              networking.ProcessId m =
                  input.readMessage(
                      networking.ProcessId.parser(),
                      extensionRegistry);
              if (processesBuilder_ == null) {
                ensureProcessesIsMutable();
                processes_.add(m);
              } else {
                processesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<networking.ProcessId> processes_ =
      java.util.Collections.emptyList();
    private void ensureProcessesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        processes_ = new java.util.ArrayList<networking.ProcessId>(processes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        networking.ProcessId, networking.ProcessId.Builder, networking.ProcessIdOrBuilder> processesBuilder_;

    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public java.util.List<networking.ProcessId> getProcessesList() {
      if (processesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(processes_);
      } else {
        return processesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public int getProcessesCount() {
      if (processesBuilder_ == null) {
        return processes_.size();
      } else {
        return processesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public networking.ProcessId getProcesses(int index) {
      if (processesBuilder_ == null) {
        return processes_.get(index);
      } else {
        return processesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder setProcesses(
        int index, networking.ProcessId value) {
      if (processesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProcessesIsMutable();
        processes_.set(index, value);
        onChanged();
      } else {
        processesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder setProcesses(
        int index, networking.ProcessId.Builder builderForValue) {
      if (processesBuilder_ == null) {
        ensureProcessesIsMutable();
        processes_.set(index, builderForValue.build());
        onChanged();
      } else {
        processesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder addProcesses(networking.ProcessId value) {
      if (processesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProcessesIsMutable();
        processes_.add(value);
        onChanged();
      } else {
        processesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder addProcesses(
        int index, networking.ProcessId value) {
      if (processesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProcessesIsMutable();
        processes_.add(index, value);
        onChanged();
      } else {
        processesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder addProcesses(
        networking.ProcessId.Builder builderForValue) {
      if (processesBuilder_ == null) {
        ensureProcessesIsMutable();
        processes_.add(builderForValue.build());
        onChanged();
      } else {
        processesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder addProcesses(
        int index, networking.ProcessId.Builder builderForValue) {
      if (processesBuilder_ == null) {
        ensureProcessesIsMutable();
        processes_.add(index, builderForValue.build());
        onChanged();
      } else {
        processesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder addAllProcesses(
        java.lang.Iterable<? extends networking.ProcessId> values) {
      if (processesBuilder_ == null) {
        ensureProcessesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, processes_);
        onChanged();
      } else {
        processesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder clearProcesses() {
      if (processesBuilder_ == null) {
        processes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        processesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public Builder removeProcesses(int index) {
      if (processesBuilder_ == null) {
        ensureProcessesIsMutable();
        processes_.remove(index);
        onChanged();
      } else {
        processesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public networking.ProcessId.Builder getProcessesBuilder(
        int index) {
      return getProcessesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public networking.ProcessIdOrBuilder getProcessesOrBuilder(
        int index) {
      if (processesBuilder_ == null) {
        return processes_.get(index);  } else {
        return processesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public java.util.List<? extends networking.ProcessIdOrBuilder> 
         getProcessesOrBuilderList() {
      if (processesBuilder_ != null) {
        return processesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(processes_);
      }
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public networking.ProcessId.Builder addProcessesBuilder() {
      return getProcessesFieldBuilder().addBuilder(
          networking.ProcessId.getDefaultInstance());
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public networking.ProcessId.Builder addProcessesBuilder(
        int index) {
      return getProcessesFieldBuilder().addBuilder(
          index, networking.ProcessId.getDefaultInstance());
    }
    /**
     * <pre>
     * be handled by the process.
     * </pre>
     *
     * <code>repeated .main.ProcessId processes = 1;</code>
     */
    public java.util.List<networking.ProcessId.Builder> 
         getProcessesBuilderList() {
      return getProcessesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        networking.ProcessId, networking.ProcessId.Builder, networking.ProcessIdOrBuilder> 
        getProcessesFieldBuilder() {
      if (processesBuilder_ == null) {
        processesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            networking.ProcessId, networking.ProcessId.Builder, networking.ProcessIdOrBuilder>(
                processes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        processes_ = null;
      }
      return processesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:main.ProcInitializeSystem)
  }

  // @@protoc_insertion_point(class_scope:main.ProcInitializeSystem)
  private static final networking.ProcInitializeSystem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new networking.ProcInitializeSystem();
  }

  public static networking.ProcInitializeSystem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProcInitializeSystem>
      PARSER = new com.google.protobuf.AbstractParser<ProcInitializeSystem>() {
    @java.lang.Override
    public ProcInitializeSystem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProcInitializeSystem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProcInitializeSystem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public networking.ProcInitializeSystem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

