// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface ProcessIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.ProcessId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * String containing either domain name  or IP (most likely)
   * </pre>
   *
   * <code>string host = 1;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <pre>
   * String containing either domain name  or IP (most likely)
   * </pre>
   *
   * <code>string host = 1;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <pre>
   * Short alias or acronym of the owner of the process
   * </pre>
   *
   * <code>string owner = 3;</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <pre>
   * Short alias or acronym of the owner of the process
   * </pre>
   *
   * <code>string owner = 3;</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <pre>
   * Process index within the owner's processes. Must be 1, 2, or 3
   * </pre>
   *
   * <code>int32 index = 4;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <pre>
   * Populated by the hub when initiating consensus with AppPropose. Do not calculate your own rank,
   * </pre>
   *
   * <code>int32 rank = 5;</code>
   * @return The rank.
   */
  int getRank();
}
