// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface ProcInitializeSystemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.ProcInitializeSystem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  java.util.List<networking.ProcessId> 
      getProcessesList();
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  networking.ProcessId getProcesses(int index);
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  int getProcessesCount();
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  java.util.List<? extends networking.ProcessIdOrBuilder> 
      getProcessesOrBuilderList();
  /**
   * <pre>
   * be handled by the process.
   * </pre>
   *
   * <code>repeated .main.ProcessId processes = 1;</code>
   */
  networking.ProcessIdOrBuilder getProcessesOrBuilder(
      int index);
}
