// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication-protocol.proto

// Protobuf Java Version: 4.26.0
package networking;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool defined = 1;</code>
   * @return The defined.
   */
  boolean getDefined();

  /**
   * <pre>
   * Value; ignore if defined == false
   * </pre>
   *
   * <code>int32 v = 2;</code>
   * @return The v.
   */
  int getV();
}
